spring:
  h2:
    console:
      enabled: true
  application:
    name: issue-book-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  
server:
  port: 9195
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost 