server:
  port: 9194
spring:
  h2:    console:      enabled: true
  cloud:
    config:      uri: http://localhost:8888
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher    
      
  application:
    name: book-api
        
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:    hostname: localhost